name=DSN Nes Emulator Universal
version=1.0.0
author=Derda
maintainer=Dsn Industries
sentence=Nofrendo NES Emulator Core for ESP32S3
paragraph=A port of Nofrendo specifically designed for ESP32-S3 with support for ST7789 display, MAX98357A I2S audio or simple buzzer, and SD card.
category=Games
url=https://github.com/derdacavga/DSN-Nes-Emulator-Universal
architectures=esp32S3
includes=nofrendo.h